// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KoordeClient is the client API for Koorde service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KoordeClient interface {
	BootStarpRPC(ctx context.Context, in *BootStrapPacket, opts ...grpc.CallOption) (*BootStrapReply, error)
	LookupRPC(ctx context.Context, in *LookupPacket, opts ...grpc.CallOption) (*PeerPacket, error)
	GetSuccessorRPC(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error)
	GetPredecessorRPC(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error)
	// UpdatePredecessor takes new pred and returns the old one
	UpdatePredecessorRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*PeerPacket, error)
	// UpdateSuccessor takes new succ and retursn the Dpointer parents that the
	// new node should contact
	UpdateSuccessorRPC(ctx context.Context, in *PeerListPacket, opts ...grpc.CallOption) (*PeerListPacket, error)
	// UpdateDPointer updates the Dpointer with new successor that should handel
	NotifyRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	UpdateDPointerRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	AddDParentRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	RemoveDParentRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	BroadCastRPC(ctx context.Context, in *BlockPacket, opts ...grpc.CallOption) (*Empty, error)
	// DEBUG RPCS
	InitBroadCastRPC(ctx context.Context, in *BlockPacket, opts ...grpc.CallOption) (*Empty, error)
	DGetBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlocksPacket, error)
	DJoin(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	DSetSuccessor(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	DSetD(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error)
	DGetID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error)
	DGetPointers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pointers, error)
	DLKup(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*PeerPacket, error)
}

type koordeClient struct {
	cc grpc.ClientConnInterface
}

func NewKoordeClient(cc grpc.ClientConnInterface) KoordeClient {
	return &koordeClient{cc}
}

func (c *koordeClient) BootStarpRPC(ctx context.Context, in *BootStrapPacket, opts ...grpc.CallOption) (*BootStrapReply, error) {
	out := new(BootStrapReply)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/BootStarpRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) LookupRPC(ctx context.Context, in *LookupPacket, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/LookupRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) GetSuccessorRPC(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/GetSuccessorRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) GetPredecessorRPC(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/GetPredecessorRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) UpdatePredecessorRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/UpdatePredecessorRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) UpdateSuccessorRPC(ctx context.Context, in *PeerListPacket, opts ...grpc.CallOption) (*PeerListPacket, error) {
	out := new(PeerListPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/UpdateSuccessorRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) NotifyRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/NotifyRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) UpdateDPointerRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/UpdateDPointerRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) AddDParentRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/AddDParentRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) RemoveDParentRPC(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/RemoveDParentRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) BroadCastRPC(ctx context.Context, in *BlockPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/BroadCastRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) InitBroadCastRPC(ctx context.Context, in *BlockPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/InitBroadCastRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DGetBlocks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BlocksPacket, error) {
	out := new(BlocksPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DGetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DJoin(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DSetSuccessor(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DSetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DSetD(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DSetD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DGetID(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DGetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DGetPointers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pointers, error) {
	out := new(Pointers)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DGetPointers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *koordeClient) DLKup(ctx context.Context, in *PeerPacket, opts ...grpc.CallOption) (*PeerPacket, error) {
	out := new(PeerPacket)
	err := c.cc.Invoke(ctx, "/rpc.Koorde/DLKup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KoordeServer is the server API for Koorde service.
// All implementations must embed UnimplementedKoordeServer
// for forward compatibility
type KoordeServer interface {
	BootStarpRPC(context.Context, *BootStrapPacket) (*BootStrapReply, error)
	LookupRPC(context.Context, *LookupPacket) (*PeerPacket, error)
	GetSuccessorRPC(context.Context, *Empty) (*PeerPacket, error)
	GetPredecessorRPC(context.Context, *Empty) (*PeerPacket, error)
	// UpdatePredecessor takes new pred and returns the old one
	UpdatePredecessorRPC(context.Context, *PeerPacket) (*PeerPacket, error)
	// UpdateSuccessor takes new succ and retursn the Dpointer parents that the
	// new node should contact
	UpdateSuccessorRPC(context.Context, *PeerListPacket) (*PeerListPacket, error)
	// UpdateDPointer updates the Dpointer with new successor that should handel
	NotifyRPC(context.Context, *PeerPacket) (*Empty, error)
	UpdateDPointerRPC(context.Context, *PeerPacket) (*Empty, error)
	AddDParentRPC(context.Context, *PeerPacket) (*Empty, error)
	RemoveDParentRPC(context.Context, *PeerPacket) (*Empty, error)
	BroadCastRPC(context.Context, *BlockPacket) (*Empty, error)
	// DEBUG RPCS
	InitBroadCastRPC(context.Context, *BlockPacket) (*Empty, error)
	DGetBlocks(context.Context, *Empty) (*BlocksPacket, error)
	DJoin(context.Context, *PeerPacket) (*Empty, error)
	DSetSuccessor(context.Context, *PeerPacket) (*Empty, error)
	DSetD(context.Context, *PeerPacket) (*Empty, error)
	DGetID(context.Context, *Empty) (*PeerPacket, error)
	DGetPointers(context.Context, *Empty) (*Pointers, error)
	DLKup(context.Context, *PeerPacket) (*PeerPacket, error)
	mustEmbedUnimplementedKoordeServer()
}

// UnimplementedKoordeServer must be embedded to have forward compatible implementations.
type UnimplementedKoordeServer struct {
}

func (UnimplementedKoordeServer) BootStarpRPC(context.Context, *BootStrapPacket) (*BootStrapReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootStarpRPC not implemented")
}
func (UnimplementedKoordeServer) LookupRPC(context.Context, *LookupPacket) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupRPC not implemented")
}
func (UnimplementedKoordeServer) GetSuccessorRPC(context.Context, *Empty) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessorRPC not implemented")
}
func (UnimplementedKoordeServer) GetPredecessorRPC(context.Context, *Empty) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredecessorRPC not implemented")
}
func (UnimplementedKoordeServer) UpdatePredecessorRPC(context.Context, *PeerPacket) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePredecessorRPC not implemented")
}
func (UnimplementedKoordeServer) UpdateSuccessorRPC(context.Context, *PeerListPacket) (*PeerListPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSuccessorRPC not implemented")
}
func (UnimplementedKoordeServer) NotifyRPC(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyRPC not implemented")
}
func (UnimplementedKoordeServer) UpdateDPointerRPC(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDPointerRPC not implemented")
}
func (UnimplementedKoordeServer) AddDParentRPC(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDParentRPC not implemented")
}
func (UnimplementedKoordeServer) RemoveDParentRPC(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDParentRPC not implemented")
}
func (UnimplementedKoordeServer) BroadCastRPC(context.Context, *BlockPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadCastRPC not implemented")
}
func (UnimplementedKoordeServer) InitBroadCastRPC(context.Context, *BlockPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitBroadCastRPC not implemented")
}
func (UnimplementedKoordeServer) DGetBlocks(context.Context, *Empty) (*BlocksPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DGetBlocks not implemented")
}
func (UnimplementedKoordeServer) DJoin(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DJoin not implemented")
}
func (UnimplementedKoordeServer) DSetSuccessor(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DSetSuccessor not implemented")
}
func (UnimplementedKoordeServer) DSetD(context.Context, *PeerPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DSetD not implemented")
}
func (UnimplementedKoordeServer) DGetID(context.Context, *Empty) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DGetID not implemented")
}
func (UnimplementedKoordeServer) DGetPointers(context.Context, *Empty) (*Pointers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DGetPointers not implemented")
}
func (UnimplementedKoordeServer) DLKup(context.Context, *PeerPacket) (*PeerPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DLKup not implemented")
}
func (UnimplementedKoordeServer) mustEmbedUnimplementedKoordeServer() {}

// UnsafeKoordeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KoordeServer will
// result in compilation errors.
type UnsafeKoordeServer interface {
	mustEmbedUnimplementedKoordeServer()
}

func RegisterKoordeServer(s grpc.ServiceRegistrar, srv KoordeServer) {
	s.RegisterService(&Koorde_ServiceDesc, srv)
}

func _Koorde_BootStarpRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootStrapPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).BootStarpRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/BootStarpRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).BootStarpRPC(ctx, req.(*BootStrapPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_LookupRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).LookupRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/LookupRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).LookupRPC(ctx, req.(*LookupPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_GetSuccessorRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).GetSuccessorRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/GetSuccessorRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).GetSuccessorRPC(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_GetPredecessorRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).GetPredecessorRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/GetPredecessorRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).GetPredecessorRPC(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_UpdatePredecessorRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).UpdatePredecessorRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/UpdatePredecessorRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).UpdatePredecessorRPC(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_UpdateSuccessorRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerListPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).UpdateSuccessorRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/UpdateSuccessorRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).UpdateSuccessorRPC(ctx, req.(*PeerListPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_NotifyRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).NotifyRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/NotifyRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).NotifyRPC(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_UpdateDPointerRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).UpdateDPointerRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/UpdateDPointerRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).UpdateDPointerRPC(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_AddDParentRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).AddDParentRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/AddDParentRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).AddDParentRPC(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_RemoveDParentRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).RemoveDParentRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/RemoveDParentRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).RemoveDParentRPC(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_BroadCastRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).BroadCastRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/BroadCastRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).BroadCastRPC(ctx, req.(*BlockPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_InitBroadCastRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).InitBroadCastRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/InitBroadCastRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).InitBroadCastRPC(ctx, req.(*BlockPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DGetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DGetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DGetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DGetBlocks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DJoin(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DSetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DSetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DSetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DSetSuccessor(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DSetD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DSetD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DSetD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DSetD(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DGetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DGetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DGetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DGetID(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DGetPointers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DGetPointers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DGetPointers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DGetPointers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Koorde_DLKup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoordeServer).DLKup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Koorde/DLKup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoordeServer).DLKup(ctx, req.(*PeerPacket))
	}
	return interceptor(ctx, in, info, handler)
}

// Koorde_ServiceDesc is the grpc.ServiceDesc for Koorde service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Koorde_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Koorde",
	HandlerType: (*KoordeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BootStarpRPC",
			Handler:    _Koorde_BootStarpRPC_Handler,
		},
		{
			MethodName: "LookupRPC",
			Handler:    _Koorde_LookupRPC_Handler,
		},
		{
			MethodName: "GetSuccessorRPC",
			Handler:    _Koorde_GetSuccessorRPC_Handler,
		},
		{
			MethodName: "GetPredecessorRPC",
			Handler:    _Koorde_GetPredecessorRPC_Handler,
		},
		{
			MethodName: "UpdatePredecessorRPC",
			Handler:    _Koorde_UpdatePredecessorRPC_Handler,
		},
		{
			MethodName: "UpdateSuccessorRPC",
			Handler:    _Koorde_UpdateSuccessorRPC_Handler,
		},
		{
			MethodName: "NotifyRPC",
			Handler:    _Koorde_NotifyRPC_Handler,
		},
		{
			MethodName: "UpdateDPointerRPC",
			Handler:    _Koorde_UpdateDPointerRPC_Handler,
		},
		{
			MethodName: "AddDParentRPC",
			Handler:    _Koorde_AddDParentRPC_Handler,
		},
		{
			MethodName: "RemoveDParentRPC",
			Handler:    _Koorde_RemoveDParentRPC_Handler,
		},
		{
			MethodName: "BroadCastRPC",
			Handler:    _Koorde_BroadCastRPC_Handler,
		},
		{
			MethodName: "InitBroadCastRPC",
			Handler:    _Koorde_InitBroadCastRPC_Handler,
		},
		{
			MethodName: "DGetBlocks",
			Handler:    _Koorde_DGetBlocks_Handler,
		},
		{
			MethodName: "DJoin",
			Handler:    _Koorde_DJoin_Handler,
		},
		{
			MethodName: "DSetSuccessor",
			Handler:    _Koorde_DSetSuccessor_Handler,
		},
		{
			MethodName: "DSetD",
			Handler:    _Koorde_DSetD_Handler,
		},
		{
			MethodName: "DGetID",
			Handler:    _Koorde_DGetID_Handler,
		},
		{
			MethodName: "DGetPointers",
			Handler:    _Koorde_DGetPointers_Handler,
		},
		{
			MethodName: "DLKup",
			Handler:    _Koorde_DLKup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/rpc.proto",
}
